### ISSUE TITLE
"invalid multibyte char" error with generator and ruby 1.9.3

### ISSUE THREAD

**Issue by dlehman** [mbillard/time_will_tell#1]
Just a note that when I ran the generator when using ruby 1.9.3, I got the following error:

```
$ rails generate time_will_tell:install
<gem path>/date_range_helper.rb:8: invalid multibyte char (US-ASCII) (SyntaxError)
```

Adding `# encoding: UTF-8` to the top of date_range_helper.rb fixed this problem:

```
# encoding: UTF-8
module TimeWillTell
...
```

**Comment by mbillard** [comment]
Closing as this was fixed with #2
