### ISSUE TITLE
It would be nice if the date_range method accepted a locale parameter

### ISSUE THREAD

**Issue by jfly** [mbillard/time_will_tell#5]
This is a problem for our application, where we want to generate English messages, regardless of the user's current locale (https://github.com/thewca/worldcubeassociation.org/issues/1128).

This gem looks unmaintained (last commit 2 years ago?), but if you're interested in reviving this gem, we could send in a PR with our changes (https://github.com/thewca/worldcubeassociation.org/pull/1133/files).

**Comment by mbillard** [comment]
I don't use it so I don't add anything to it. There weren't any issues as far as I know. If you submit a PR I can take a look and merge it.

**Comment by jfly** [comment]
After creating this issue, I discovered the existence of [`I18n.with_locale`](http://www.rubydoc.info/gems/activesupport/2.3.17/I18n.with_locale), which seems to be built with this use case precisely in mind. Closing this issue.

**Comment by mbillard** [comment]
Glad you found a way to make it work. Feel free to suggest improvements or submit PRs in the future, I'll look at them even if I'm not actively maintaining the gem.
